openapi: 3.0.0
info:
  title: Messenger.
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development server

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Authorization user .
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"
      responses:
        201:
          description: Token created.
        400:
          description: No such user exists or wrong password.
        500:
          description: Server error.

  /auth/sing-up:
    post:
      tags:
        - Auth
      summary: Registration user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/singUpUser"
      responses:
        201:
          description: User registered.
        409:
          description: User with this email already exists.
        500:
          description: Server error.

  /profile/update:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Profile
      summary: Update user data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateProfile"
      responses:
        201:
          description: User update.
        400:
          description: User with this email already exists.
        401:
          description: Not authorized.
        500:
          description: Server error.

  /profile/change-password:
    patch:
      security:
        - bearerAuth: []
      tags:
        - Profile
      summary: Update password .
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/changePasswordProfile"
      responses:
        201:
          description: Password changed in database.
        400:
          description: Wrong password.
        401:
          description: Not authorized.
        500:
          description: Server error.

  /profile/destroy:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Profile
      summary: Delete user.
      responses:
        200:
          description: Succes.
        401:
          description: Not authorized.
        500:
          description: Server error.

  /use-cases/find-all:
    get:
      tags:
        - UseCases
      summary: List all users.
      responses:
        200:
          description: Succes.
        500:
          description: Server error.

  /use-cases/search:
    get:
      security:
        - bearerAuth: []
      tags:
        - UseCases
      summary: Search users and group .
      parameters:
        - in: query
          name: searchText
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 100
          description: Search query string.
      responses:
        200:
          description: Succes.
        401:
          description: Not authorized.
        500:
          description: Server error.

  /use-cases/mark-as-deleted:
    post:
      security:
        - bearerAuth: []
      tags:
        - UseCases
      summary: Delete messages for user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - companionId
              properties:
                companionId:
                  type: string
                  format: uuid
                  description: ID of the conversation companion
                  example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        200:
          description: Delete message succes.
        401:
          description: Not authorized.
        500:
          description: Server error.

  /use-cases/create-group:
    post:
      security:
        - bearerAuth: []
      tags:
        - UseCases
      summary: Create new group.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createGroup"
      responses:
        200:
          description: Create group succes.
        401:
          description: Not authorized.
        500:
          description: Server error.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    singUpUser:
      type: object
      additionalProperties: false
      required:
        - password
        - email
        - firstName
      properties:
        firstName:
          type: string
          pattern: "^\\S+$"
          description: User first name
          example: Don
        lastName:
          type: string
          pattern: '^\S*$'
          description: User last name
          example: Stell
        email:
          type: string
          pattern: "^\\S+$"
          description: User email
          example: admin@example.com
        password:
          type: string
          pattern: "^\\S+$"
          description: User password
          example: "1234"

    loginUser:
      type: object
      additionalProperties: false
      required:
        - password
        - email
      properties:
        email:
          type: string
          description: User email
          example: admin@example.com
        password:
          type: string
          description: Password user.
          example: "1234"

    updateProfile:
      type: object
      additionalProperties: false
      properties:
        firstName:
          type: string
          pattern: "^\\S+$"
          description: User first name.
          example: Derek
        lastName:
          type: string
          pattern: "^\\S+$"
          description: User last name.
          example: Jordan

    changePasswordProfile:
      type: object
      additionalProperties: false
      required:
        - oldPassword
        - newPassword
      properties:
        oldPassword:
          type: string
          pattern: "^\\S+$"
          description: Old user password
          example: "1234"
        newPassword:
          type: string
          pattern: "^\\S+$"
          description: New user password
          example: "12345"

    createGroup:
      type: object
      additionalProperties: false
      required:
        - groupId
        - groupName
        - notificationMessage
        - messageId
      properties:
        groupId:
          type: string
          pattern: "^\\S+$"
          description: id in uuid format
          example: "123e4567-e89b-12d3-a456-426614174000"
        groupName:
          type: string
          pattern: "^\\S+$"
          description: Group name
          example: "Travel"
        notificationMessage:
          type: string
          description: Notification message
          example: "Group create"
        messageId:
          type: string
          pattern: "^\\S+$"
          description: id in uuid format
          example: "123e4567-e89b-12d3-a456-426614174000"
