const NUMBER_OF_USERS = 10;
const NUMBER_OF_GROUPS = 6;
const NUMBER_OF_USERS_GROUPS = 60;
const NUMBER_OF_MESSAGES = 50;
const NUMBER_OF_IMAGES = 30;

module.exports = {
  NUMBER_OF_GROUPS,
  NUMBER_OF_USERS,
  NUMBER_OF_USERS_GROUPS,
  NUMBER_OF_MESSAGES,
  NUMBER_OF_IMAGES,
};
